INSERT INTO USER_ROLE (ID, ROLE,DESCRIPTION) VALUES (1, 'CEO','Executive of operations');
INSERT INTO USER_ROLE (ID, ROLE,DESCRIPTION) VALUES (2, 'CSRA', 'Customer Service Representative Admin');
INSERT INTO USER_ROLE (ID, ROLE,DESCRIPTION) VALUES (3, 'EMPLOYEE', 'Employee of the health department');
INSERT INTO USER_ROLE (ID, ROLE,DESCRIPTION) VALUES (4, 'CUSTOMER', 'Patient of the health department');

INSERT INTO VACCINATION_STATUS(ID, VACCINATED, VACCINATION_DATE, CREATED_DATE, LAST_MODIFIED_DATE) VALUES (1, 'Y', CURRENT_TIMESTAMP()-2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO
USERS (ID,FIRSTNAME,MIDDLE,LASTNAME,USERNAME,PASSWORD,ADDRESS,ADDRESS2,CITY,STATE, ZIP, PHONE,EMAIL, ROLE_ID, VACCINATION_STATUS_ID)
VALUES (1, 'JANE', 'D', 'DOE', 'JDOE1', 'PASS', '123 STREET', null, 'DOVER', 'NEW HAMPSHIRE', '03456-3456', '123-948-5762', 'jane@gmail.com', 1, 1);
INSERT INTO
USERS (ID,FIRSTNAME,MIDDLE,LASTNAME,USERNAME,PASSWORD,ADDRESS,ADDRESS2,CITY,STATE, ZIP, PHONE,EMAIL, ROLE_ID, VACCINATION_STATUS_ID)
VALUES (2, 'DON', 'E', 'PARKER', 'DonnyPark', 'PASS', '123 STREET', null, 'DOVER', 'NEW HAMPSHIRE', '03456-3456', '245-987-6302', 'DonnyPark@gmail.com', 2, null);
INSERT INTO
USERS (ID,FIRSTNAME,MIDDLE,LASTNAME,USERNAME,PASSWORD,ADDRESS,ADDRESS2,CITY,STATE, ZIP, PHONE,EMAIL, ROLE_ID, VACCINATION_STATUS_ID)
VALUES (3, 'JOHN', 'B', 'WILLIAMS', 'JoWill2', 'PASS', '123 STREET', null, 'DOVER', 'NEW HAMPSHIRE', '03456-3456', '528-794-6350', 'JoWill2@gmail.com', 3, null);
INSERT INTO
USERS (ID,FIRSTNAME,MIDDLE,LASTNAME,USERNAME,PASSWORD,ADDRESS,ADDRESS2,CITY,STATE, ZIP, PHONE,EMAIL, ROLE_ID, VACCINATION_STATUS_ID)
VALUES (4, 'MARY', NULL, 'COLE', 'MarCole1', 'PASS', '123 STREET', null, 'DOVER', 'NEW HAMPSHIRE', '03456-3456', '264-582-0346', 'MarCole1@gmail.com', 4, null);

INSERT INTO TEST_RESULTS(ID,USER_ID,STATUS,TEST_DATE, CREATED_DATE,LAST_MODIFIED_DATE) VALUES(1, 1, 'U', CURRENT_TIMESTAMP()-1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());