CREATE TABLE USERS (
    ID NUMBER,
    FIRSTNAME VARCHAR(100) NOT NULL,
    MIDDLE CHAR(1),
    LASTNAME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    ADDRESS2 VARCHAR(50),
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(100) NOT NULL,
    ZIP VARCHAR(10) NOT NULL,
    PHONE VARCHAR(10),
    EMAIL VARCHAR(200),
    ROLE_ID NUMBER NOT NULL
    );

CREATE TABLE USER_ROLE (
    ID NUMBER,
    NAME VARCHAR(8)
);

INSERT INTO
USERS (ID,FIRSTNAME,MIDDLE,LASTNAME,USERNAME,PASSWORD,ADDRESS,ADDRESS2,CITY,STATE, ZIP, PHONE,EMAIL,ROLE_ID)
VALUES (1, 'JANE', 'D', 'DOE', 'JDOE1', 'PASS', '123 STREET', null, 'DOVER', 'NEW HAMPSHIRE', '03456-3456', '123948576', 'jane@gmail.com', 1);
INSERT INTO
USERS (ID,FIRSTNAME,MIDDLE,LASTNAME,USERNAME,PASSWORD,ADDRESS,ADDRESS2,CITY,STATE, ZIP, PHONE,EMAIL,ROLE_ID)
VALUES (2, 'DON', 'E', 'PARKER', 'DonnyPark', 'PASS', '123 STREET', null, 'DOVER', 'NEW HAMPSHIRE', '03456-3456', '2459876302', 'DonnyPark@gmail.com', 2);
INSERT INTO
USERS (ID,FIRSTNAME,MIDDLE,LASTNAME,USERNAME,PASSWORD,ADDRESS,ADDRESS2,CITY,STATE, ZIP, PHONE,EMAIL,ROLE_ID)
VALUES (3, 'JOHN', 'B', 'WILLIAMS', 'JoWill2', 'PASS', '123 STREET', null, 'DOVER', 'NEW HAMPSHIRE', '03456-3456', '5287946350', 'JoWill2@gmail.com', 3);
INSERT INTO
USERS (ID,FIRSTNAME,MIDDLE,LASTNAME,USERNAME,PASSWORD,ADDRESS,ADDRESS2,CITY,STATE, ZIP, PHONE,EMAIL,ROLE_ID)
VALUES (4, 'MARY', NULL, 'COLE', 'MarCole1', 'PASS', '123 STREET', null, 'DOVER', 'NEW HAMPSHIRE', '03456-3456', '2645820346', 'MarCole1@gmail.com', 4);

INSERT INTO USER_ROLE (ID, NAME) VALUES (1, 'CEO');
INSERT INTO USER_ROLE (ID, NAME) VALUES (2, 'CSRA');
INSERT INTO USER_ROLE (ID, NAME) VALUES (3, 'EMPLOYEE');
INSERT INTO USER_ROLE (ID, NAME) VALUES (4, 'CUSTOMER');