INSERT INTO USER_ROLE (ID, ROLE,DESCRIPTION) VALUES (1, 'CEO','Executive of operations');
INSERT INTO USER_ROLE (ID, ROLE,DESCRIPTION) VALUES (2, 'CSRA', 'Customer Service Representative Admin');
INSERT INTO USER_ROLE (ID, ROLE,DESCRIPTION) VALUES (3, 'EMPLOYEE', 'Employee of the health department');
INSERT INTO USER_ROLE (ID, ROLE,DESCRIPTION) VALUES (4, 'CUSTOMER', 'Patient of the health department');

INSERT INTO USERS (ID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,ADDRESS,ADDRESS2,CITY,STATE, ZIP, PHONE,EMAIL, ROLE_ID) VALUES (1, 'JANE', 'DOE', 'JDOE1', '$2a$10$Xh8vC9LtitYAlxtYoD4KOuS1y5SN1G/tzPdqXt//mWiMs5xDVro6e', '123 STREET', null, 'DOVER', 'NEW HAMPSHIRE', '03456-3456', '123-948-5762', 'jane@gmail.com', 1);
--Password is PASS
INSERT INTO USERS (ID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,ADDRESS,ADDRESS2,CITY,STATE, ZIP, PHONE,EMAIL, ROLE_ID) VALUES (2, 'DON', 'PARKER', 'DonnyPark', '$2a$10$Xh8vC9LtitYAlxtYoD4KOuS1y5SN1G/tzPdqXt//mWiMs5xDVro6e', '123 STREET', null, 'DOVER', 'NEW HAMPSHIRE', '03456-3456', '245-987-6302', 'DonnyPark@gmail.com', 2);
INSERT INTO USERS (ID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,ADDRESS,ADDRESS2,CITY,STATE, ZIP, PHONE,EMAIL, ROLE_ID) VALUES (3, 'JOHN', 'WILLIAMS', 'JoWill2', '$2a$10$Xh8vC9LtitYAlxtYoD4KOuS1y5SN1G/tzPdqXt//mWiMs5xDVro6e', '123 STREET', null, 'DOVER', 'NEW HAMPSHIRE', '03456-3456', '528-794-6350', 'JoWill2@gmail.com', 3);
INSERT INTO USERS (ID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,ADDRESS,ADDRESS2,CITY,STATE, ZIP, PHONE,EMAIL, ROLE_ID) VALUES (4, 'MARY', 'COLE', 'MarCole1', '$2a$10$Xh8vC9LtitYAlxtYoD4KOuS1y5SN1G/tzPdqXt//mWiMs5xDVro6e', '123 STREET', null, 'DOVER', 'NEW HAMPSHIRE', '03456-3456', '264-582-0346', 'MarCole1@gmail.com', 4);

INSERT INTO TEST_RESULTS(USER_ID,STATUS,TEST_DATE, CREATED_DATE,LAST_MODIFIED_DATE) VALUES(1, 'U', CURRENT_TIMESTAMP()-1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO VACCINATION_STATUS(USER_ID, VACCINATION_DATE, VACCINE_TYPE, CREATED_DATE, LAST_MODIFIED_DATE) VALUES (1, CURRENT_TIMESTAMP()-2,'Comirnaty/Pfizer-Dose1', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
