CREATE TABLE USERS (
    ID NUMBER,
    FIRSTNAME VARCHAR(100) NOT NULL,
    MIDDLE CHAR(1),
    LASTNAME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    ADDRESS2 VARCHAR(50),
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(100) NOT NULL,
    ZIP VARCHAR(10) NOT NULL,
    PHONE VARCHAR(10),
    EMAIL VARCHAR(200),
    ROLE_ID NUMBER NOT NULL
    );

CREATE TABLE USER_ROLE (
    ID NUMBER,
    ROLE VARCHAR(8)
);